# Generated by Django 4.2.11 on 2024-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogpost_blogdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Blogger',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
