# Generated by Django 4.2.11 on 2024-03-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_reader_userid_delete_blogger_delete_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='NumberOfMembers',
            field=models.IntegerField(default=0),
        ),
    ]
