# Generated by Django 4.2.11 on 2024-04-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_community_creatorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
